

class Tester:
  """Tester Class

  This class is in charge of performing the latency tests for the chosen exchange.

  Instance Properties:
    Credentials:
      api_key: str
      api_secret: str
        The credentials generated by the exchange.

    Results:
      ...
  """
  def __init__(self, api_key: str, api_secret: str):
    self.api_key = api_key
    self.api_secret = api_secret